// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWFLF-or1lm-OXYaBHqF-o-XHdfqlKTrE',
    appId: '1:788634986628:web:4eba8679acd135c413fad1',
    messagingSenderId: '788634986628',
    projectId: 'fir-app-eaa38',
    authDomain: 'fir-app-eaa38.firebaseapp.com',
    storageBucket: 'fir-app-eaa38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbhbdvW9aLc0XxP7DW8Xn5awE1a6fFCE',
    appId: '1:788634986628:android:33a41ee6eb93159113fad1',
    messagingSenderId: '788634986628',
    projectId: 'fir-app-eaa38',
    storageBucket: 'fir-app-eaa38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChjvMEe6DJPJXmxiQD2EcGZz94bZfULDc',
    appId: '1:788634986628:ios:feba91e1d2c678e613fad1',
    messagingSenderId: '788634986628',
    projectId: 'fir-app-eaa38',
    storageBucket: 'fir-app-eaa38.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChjvMEe6DJPJXmxiQD2EcGZz94bZfULDc',
    appId: '1:788634986628:ios:feba91e1d2c678e613fad1',
    messagingSenderId: '788634986628',
    projectId: 'fir-app-eaa38',
    storageBucket: 'fir-app-eaa38.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWFLF-or1lm-OXYaBHqF-o-XHdfqlKTrE',
    appId: '1:788634986628:web:ad7eeb32fcfcc8d313fad1',
    messagingSenderId: '788634986628',
    projectId: 'fir-app-eaa38',
    authDomain: 'fir-app-eaa38.firebaseapp.com',
    storageBucket: 'fir-app-eaa38.firebasestorage.app',
  );

}